### ISSUE TITLE
Typo in metadata leads to dependency not being installed

### ISSUE THREAD

**Issue by mattburgess** [jtyr/ansible-stunnel#1]
https://github.com/jtyr/ansible-stunnel/blob/master/meta/main.yml#L16 should read 'jtyr.config_encoder_filters'.  Without the author-name prefix, ansible-galaxy fails to pull down and install that role.  According to the docs at https://galaxy.ansible.com/intro#meta it should actually be:

```
dependencies:
  - { role: jtyr.config_encoder_filters }
```

But ansible-galaxy seems happy enough with the current format.

**Comment by jtyr** [comment]
Thanks for your comment, @MattBurgess. The format without the username prefix is intentional. Please read the [Installation](https://github.com/jtyr/ansible-config_encoder_filters#installation) instructions for more details about how to install the dependency.

**Comment by mattburgess** [comment]
Great, thanks for the super quick reply!  I won't pretend to understand why you want it installed that way (it's the only role I've come across so far that requires this setup) but it's documented and the documentation is accurate so it's all good!
